### ISSUE TITLE
'Women' doesn't lemmatized to 'woman'

### ISSUE THREAD

**Issue by haukot** [winkjs/wink-lemmatizer#15]
The issue as in the title. Meanwhile 'men' is lemmatized to 'man'.

I'm using wink-lemmatizer 3.0.1

**Comment by sanjayaksaxena** [comment]
Hi @haukot, Thanks for highlighting the miss — will fix it shortly.

**Comment by sanjayaksaxena** [comment]
Have fixed and released [v3.0.2](https://www.npmjs.com/package/wink-lemmatizer) — please upgrade.
