### ISSUE TITLE
Any plans for other languages?

### ISSUE THREAD

**Issue by deemeetree** [winkjs/wink-lemmatizer#16]
What a great module! Any plans for other languages? Also, what if the POS is not identified? Maybe add a way to produce the lemma anyway (e.g. through iterating verbs, adj, nouns and delivering the first change). Would be happy to contribute.

**Comment by sanjayaksaxena** [comment]
Hello @deemeetree 

Delighted to learn that you are finding **winkjs** modules useful.

[Contributions](https://github.com/winkjs/wink-lemmatizer/blob/master/CONTRIBUTING.md) are always welcome. In absence of POS, the other alternative could be to produce multiple lemmas — one per applicable POS. We will be happy to help you on this. 

As far as other languages are concerned, we are planning to build [language models](https://github.com/winkjs/wink-eng-lite-model#wink-eng-lite-model) for [wink-nlp](https://github.com/winkjs/wink-nlp#winknlp) and then release lemmatizer part here as well. One can do it other way round as well, i.e.build other language lemmatizers first and use them with wink-nlp.
