### ISSUE TITLE
scouring/devouring return incorrect lemma

### ISSUE THREAD

**Issue by ekolve** [winkjs/wink-lemmatizer#2]
I ran these in the browser using npmjs.org:

```javascript
wl.lemmatizeVerb("scouring"); // return'scou'

wl.lemmatizeVerb("devouring"); // return 'devou'

```
These should return scour and devour respectively.

**Comment by sanjayaksaxena** [comment]
Hello @ekolve 

We are in the process of upgrading this version to leverage **wordnet**. The lemmatizer falls back on porter stemmer, in case it is not able to figure out the lemma. What you are observing is the result of stemming!

We should be releasing the new version in about a weeks time.

Best,
Sanjaya
