### ISSUE TITLE
[Feature Request] Automatically detect type of word (noun, verb, ...)

### ISSUE THREAD

**Issue by searleser97** [winkjs/wink-lemmatizer#25]
I think it would be nice if we could just send an entire sentence to the api
and it returned the lemmatized sentence, instead of having to find out
what is the type of each word we want to lemmatize

**Comment by sanjayaksaxena** [comment]
@searleser97 thanks for your suggestion.

This package is only meant for lemmatization. If you are looking for an integrated NLP package, please consider [wink-nlp](https://github.com/winkjs/wink-nlp). It has the requested capability and much more. If you are interested only in what you have asked then please look at this runkit example — https://runkit.com/sanjaya/6137781a7349340008a99d91

Its documentation can be found at https://winkjs.org/wink-nlp/getting-started.html and you may like to explore some interesting Observable notebooks at https://observablehq.com/collection/@winkjs/winknlp-recipes

**Comment by searleser97** [comment]
looks good, thanks for the answer
