### ISSUE TITLE
How to override some words?

### ISSUE THREAD

**Issue by lazharichir** [winkjs/wink-lemmatizer#9]
Some results are correct syntactically but do not make sense in our project. For example, `singular("data")` returns `datum` which is correct but we would prefer `data` to be returned.

Is there a way to override that?

**Comment by sanjayaksaxena** [comment]
Hi @lazharichir 

Currently there is no way to override. As a workaround, you could maintain noun/verb/adjective-wise exceptions lookup table to address your need.

Best,
Sanjaya

**Comment by sanjayaksaxena** [comment]
Hope it helped. Closing the issue for now.

Best,
Sanjaya
